version: '3.8'
services:

  frontend:
    image: mirosiakyakipara/foodgram-frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
      - static_value:/app/build/static/
      - media_value:/app/build/media/

  db:
    image: postgres:13.0-alpine
    volumes:
      - db:/var/lib/postgresql/data/
    env_file:
      - ./.env
    
  backend:
    image: mirosiakyakipara/foodgram-backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/ 
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
      - frontend

volumes:
  db:
  static_value:
  media_value:
  